apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: toducze-test
  labels:
    app: postgres
spec:
  storageClassName: nfs-client 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
